export const WORDS_REQUEST = 'WORDS_REQUEST';
export const WORDS_SUCCESS = 'WORDS_SUCCESS';
export const WORDS_FAILURE = 'WORDS_FAILURE';

export const INFO_WORDS_REQUEST = 'INFO_WORDS_REQUEST';
export const INFO_WORDS_SUCCESS = 'INFO_WORDS_SUCCESS';
export const INFO_WORDS_FAILURE = 'INFO_WORDS_FAILURE';