export const SETTINGS_REQUEST = 'SETTINGS_REQUEST';
export const SETTINGS_UPDATE  = 'SETTINGS_UPDATE';
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';
export const SETTINGS_FAILURE = 'SETTINGS_FAILURE';
